site_name: Guia de utilização - Prisma
site_url: https://mydomain.org/guia_utilizacao
theme:
  name:  material   
  language: pt-BR
  logo: Simbolo.png
  favicon: Simbolo.png
  palette: 
    - scheme: default
      primary: 'white'
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: 'black'
      toggle:
        icon: material/weather-sunny
        name: Modo claro
#extra_css:
  #- extra.css
nav:
 - Página Inicial: 'index.md'
 - Simulador de Cenários:
    - 'Gantt': 'ganttcenario.md'
    - 'Painel de Serviços': 'painelservicos.md'
    - 'Painel de Materiais': 'painelmateriais.md'
- Abrir Cenário: 'abrircenario.md'
- Gerar Cenário: 'gerarcenario.md'
- Acessar Escopo Atual: 
    - 'Gantt': 'escopoatual.md'
    - 'Painel de Serviços': 'painelservicos.md'
    - 'Painel de Materiais': 'painelmateriais.md'
- Painel de Publicações: 'publicacoes.md'
- Visão Operacional: 'visaooperacional.md'
- Visão Médio-Prazo: 'visaomedioprazo.md'
- Visão Contratual: 'visaocontratual.md'
