site_name: Guia de utilização - Prisma
site_url: https://mydomain.org/guia_utilizacao
theme:
  name:  material   
  language: pt-BR
  
  favicon: Simbolo.png
  palette: 
    - scheme: default
      primary: 'white'
      logo: Simbolo.png
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: 'black'
      logo: Vector.png
      toggle:
        icon: material/weather-sunny
        name: Modo claro
#extra_css:
  #- stylesheets/extra.css
nav:
 - Início: 'index.md'
 - Sobre:
    - 'Referências': 'sobre.md'
